### PR TITLE
d.js v13 rework

### LINKED ISSUE #182: Counter Bug
https://zeppelin.gg/docs/setup-guides/counters

            condition: "=0"

gives an error

### LINKED ISSUE #183: AvatarURL broken
Avatar for embed logs e.g in thumbnail fields are currently broken

### LINKED ISSUE #237: Include sticker info in !source
Currently, the `source` command works with message ID, content, attachments, and embeds, but not stickers (which are of course now released for custom uploading), so I think that should also be supported.

Example:
```json
{
  "id": "859858669486342176",
  "content": "",
  "attachments": [],
  "embeds": [],
  "stickers": {
    "id": "1234",
    "name": "pogcow"
  }
}
```

### PR DESCRIPTION
**Pull request by DarkView**
Fully rewrites Zeppelin into using Discord.js instead of Eris.
This introduces the possibility of Buttons and other Interaction Components and enables Threads for all commands and automod functions.

**This should be ready to release, though there are almost guaranteed to be issues that need to be fixed quickly that are hard to debug on my own.**
All compiler errors are fixed and things like waitForReaction are replaced with waitForButton.
Reaction Roles now supports buttons through special config options.
Threads work by default as messageCreate is enabled for Threads in APIv9.

This PR depends on [PR 10 on Knub](https://github.com/Dragory/Knub/pull/10).
This PR closes #183, closes #237, closes #182

### CODE REVIEW

File: backend/src/plugins/Mutes/commands/MutesCmd.ts [hunk 1]
```diff
@@ -27,10 +27,17 @@ export const MutesCmd = mutesCmd({
     let totalMutes = 0;
     let hasFilters = false;
 
-    let stopCollectionFn;
-    let stopCollectionTimeout;
+    let stopCollectionFn = () => {
+      return;
+    };
```
Comment (almeidx) [inline backend/src/plugins/Mutes/commands/MutesCmd.ts:32]:
```suggestion
    let stopCollectionFn = () => {};
```

**Review by almeidx — CHANGES_REQUESTED** [review]

File: backend/src/plugins/Mutes/commands/MutesCmd.ts (hunk 1 above)
Comment (DarkView) [reply backend/src/plugins/Mutes/commands/MutesCmd.ts:32]: This would return an error because of an empty block.
I would prefer to do this instead of telling tslint to ignore it.

Comment (almeidx) [reply backend/src/plugins/Mutes/commands/MutesCmd.ts:32]: What about `() => void 0;`?

File: backend/src/data/GuildArchives.ts [hunk 2]
```diff
@@ -1,5 +1,6 @@
 import { Guild, Snowflake } from "discord.js";
 import moment from "moment-timezone";
+import { isDefaultSticker } from "src/utils/isDefaultSticker";
```
Comment (almeidx) [inline backend/src/data/GuildArchives.ts:3]:
```suggestion
import { isDefaultSticker } from "../utils/isDefaultSticker";
```

File: backend/src/plugins/Automod/functions/setAntiraidLevel.ts [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import { User } from "discord.js";
 import { GuildPluginData } from "knub";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/Automod/functions/setAntiraidLevel.ts:3]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/Censor/util/censorMessage.ts [hunk 4]
```diff
@@ -1,9 +1,10 @@
-import { Snowflake, TextChannel } from "discord.js";
+import { Snowflake, TextChannel, User } from "discord.js";
 import { GuildPluginData } from "knub";
 import { deactivateMentions, disableCodeBlocks } from "knub/dist/helpers";
+import { channelToConfigAccessibleChannel, userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/Censor/util/censorMessage.ts:4]:
```suggestion
import { channelToConfigAccessibleChannel, userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/Logs/util/onMessageDelete.ts [hunk 5]
```diff
@@ -1,15 +1,16 @@
-import { MessageAttachment, Snowflake } from "discord.js";
+import { MessageAttachment, Snowflake, User } from "discord.js";
 import { GuildPluginData } from "knub";
 import moment from "moment-timezone";
+import { channelToConfigAccessibleChannel, userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/Logs/util/onMessageDelete.ts:4]:
```suggestion
import { channelToConfigAccessibleChannel, userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/Logs/util/onMessageUpdate.ts [hunk 6]
```diff
@@ -1,6 +1,7 @@
-import { MessageEmbed, Snowflake } from "discord.js";
+import { MessageEmbed, Snowflake, User } from "discord.js";
 import { GuildPluginData } from "knub";
 import cloneDeep from "lodash.clonedeep";
+import { channelToConfigAccessibleChannel, userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/Logs/util/onMessageUpdate.ts:4]:
```suggestion
import { channelToConfigAccessibleChannel, userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/commands/AddCaseCmd.ts [hunk 7]
```diff
@@ -1,10 +1,11 @@
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/commands/AddCaseCmd.ts:1]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/commands/BanCmd.ts [hunk 8]
```diff
@@ -1,11 +1,13 @@
+import { User } from "discord.js";
 import humanizeDuration from "humanize-duration";
 import { getMemberLevel } from "knub/dist/helpers";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/commands/BanCmd.ts:4]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/commands/DeleteCaseCmd.ts [hunk 9]
```diff
@@ -1,5 +1,6 @@
 import { TextChannel } from "discord.js";
 import { helpers } from "knub";
+import { memberToConfigAccessibleMember } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/commands/DeleteCaseCmd.ts:3]:
```suggestion
import { memberToConfigAccessibleMember } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/commands/ForcebanCmd.ts [hunk 10]
```diff
@@ -1,10 +1,11 @@
 import { Snowflake } from "discord.js";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/commands/ForcebanCmd.ts:2]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/commands/MassBanCmd.ts [hunk 11]
```diff
@@ -1,6 +1,7 @@
 import { Snowflake, TextChannel } from "discord.js";
 import { waitForReply } from "knub/dist/helpers";
 import { performance } from "perf_hooks";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/commands/MassBanCmd.ts:4]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/commands/MassUnbanCmd.ts [hunk 12]
```diff
@@ -1,5 +1,6 @@
 import { Snowflake, TextChannel } from "discord.js";
 import { waitForReply } from "knub/dist/helpers";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/commands/MassUnbanCmd.ts:3]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/AutoDelete/util/deleteNextItem.ts [hunk 13]
```diff
@@ -1,9 +1,10 @@
-import { Permissions, Snowflake, TextChannel } from "discord.js";
+import { Permissions, Snowflake, TextChannel, User } from "discord.js";
 import { GuildPluginData } from "knub";
 import moment from "moment-timezone";
+import { channelToConfigAccessibleChannel, userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/AutoDelete/util/deleteNextItem.ts:4]:
```suggestion
import { channelToConfigAccessibleChannel, userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/Automod/actions/reply.ts [hunk 14]
```diff
@@ -1,12 +1,12 @@
 import { MessageOptions, Permissions, Snowflake, TextChannel, User } from "discord.js";
 import * as t from "io-ts";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/Automod/actions/reply.ts:3]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/commands/MassmuteCmd.ts [hunk 15]
```diff
@@ -1,5 +1,6 @@
 import { Snowflake, TextChannel } from "discord.js";
 import { waitForReply } from "knub/dist/helpers";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/commands/MassmuteCmd.ts:3]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/commands/NoteCmd.ts [hunk 16]
```diff
@@ -1,8 +1,10 @@
+import { User } from "discord.js";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/commands/NoteCmd.ts:2]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/commands/UnbanCmd.ts [hunk 17]
```diff
@@ -1,10 +1,11 @@
 import { Snowflake } from "discord.js";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/commands/UnbanCmd.ts:2]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/events/CreateBanCaseOnManualBanEvt.ts [hunk 18]
```diff
@@ -1,4 +1,5 @@
 import { GuildAuditLogs, User } from "discord.js";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/events/CreateBanCaseOnManualBanEvt.ts:2]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/events/CreateKickCaseOnManualKickEvt.ts [hunk 19]
```diff
@@ -1,9 +1,10 @@
 import { GuildAuditLogs, User } from "discord.js";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/events/CreateKickCaseOnManualKickEvt.ts:2]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/events/CreateUnbanCaseOnManualUnbanEvt.ts [hunk 20]
```diff
@@ -1,8 +1,9 @@
 import { GuildAuditLogs, User } from "discord.js";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/events/CreateUnbanCaseOnManualUnbanEvt.ts:2]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

File: backend/src/plugins/ModActions/functions/banUserId.ts [hunk 21]
```diff
@@ -1,6 +1,7 @@
 import { DiscordAPIError, Snowflake, User } from "discord.js";
 import humanizeDuration from "humanize-duration";
 import { GuildPluginData } from "knub";
+import { userToConfigAccessibleUser } from "src/utils/configAccessibleObjects";
```
Comment (almeidx) [inline backend/src/plugins/ModActions/functions/banUserId.ts:4]:
```suggestion
import { userToConfigAccessibleUser } from "../../../utils/configAccessibleObjects";
```

**Review by almeidx — CHANGES_REQUESTED** [review]
There were a few more but I got tired ¯\\_(ツ)\_/¯

File: backend/src/commandTypes.ts [hunk 22]
```diff
@@ -74,16 +72,16 @@ export const commandTypes = {
 
   async anyId(value: string, context: CommandContext<any>) {
     const userId = resolveUserId(context.pluginData.client, value);
```
Comment (almeidx) [inline backend/src/commandTypes.ts:74]: This function should return a Snowflake so you don't need to use type assertion after using it

File: backend/src/commandTypes.ts [hunk 23]
```diff
@@ -74,16 +72,16 @@ export const commandTypes = {
...
 
     const channelIdMatch = value.match(channelMentionRegex);
-    if (channelIdMatch) return channelIdMatch[1];
+    if (channelIdMatch) return channelIdMatch[1] as Snowflake;
 
     const roleIdMatch = value.match(roleMentionRegex);
-    if (roleIdMatch) return roleIdMatch[1];
+    if (roleIdMatch) return roleIdMatch[1] as Snowflake;
 
     if (isValidSnowflake(value)) {
```
Comment (almeidx) [inline backend/src/commandTypes.ts:83]: `isValidSnowflake` should return `value is Snowflake` so you don't have to use type assertion afterwards

File: backend/src/data/DefaultLogMessages.json [hunk 24]
```diff
@@ -24,11 +24,15 @@
 
   "CHANNEL_CREATE": "🖊 Channel {channelMention(channel)} was created",
   "CHANNEL_DELETE": "🗑 Channel {channelMention(channel)} was deleted",
-  "CHANNEL_EDIT": "✏ Channel {channelMention(channel)} was edited",
+  "CHANNEL_UPDATE": "✏ Channel {channelMention(newChannel)} was edited. Changes:\n{differenceString}",
+
+  "THREAD_CREATE": "🖊 Thread {channelMention(thread)} was created in channel <#{thread.parentID}>",
```
Comment (almeidx) [inline backend/src/data/DefaultLogMessages.json:29]:
```suggestion
  "THREAD_CREATE": "🖊 Thread {channelMention(thread)} was created in channel <#{thread.parentId}>",
```

File: backend/src/data/DefaultLogMessages.json [hunk 25]
```diff
@@ -24,11 +24,15 @@
...
+  "THREAD_DELETE": "🗑 Thread {channelMention(thread)} was deleted/archived from channel <#{thread.parentID}>",
```
Comment (almeidx) [inline backend/src/data/DefaultLogMessages.json:30]:
```suggestion
  "THREAD_DELETE": "🗑 Thread {channelMention(thread)} was deleted/archived from channel <#{thread.parentId}>",
```

File: backend/src/data/GuildArchives.ts [hunk 26]
```diff
@@ -73,13 +74,19 @@ export class GuildArchives extends BaseGuildRepository {
   protected async renderLinesFromSavedMessages(savedMessages: SavedMessage[], guild: Guild) {
     const msgLines: string[] = [];
     for (const msg of savedMessages) {
-      const channel = guild.channels.get(msg.channel_id);
+      const channel = guild.channels.cache.get(msg.channel_id as Snowflake);
```
Comment (almeidx) [inline backend/src/data/GuildArchives.ts:77]: The SavedMessage interface should have `channel_id` typed as Snowflake

**Review by almeidx — APPROVED** [review]
